### ISSUE TITLE
Rename project

### ISSUE THREAD

**Issue by nomiro** [nomiro/obelist#27]
I would like a project name that is:

- Less tied to GitHub specifically (perhaps this project could be useful for other Git platforms)
- Perhaps is a bit less focused on the "note" aspect and incorporate the wrapping of lint tools to produce more useful action as well as the wrapping of lint tools for the purpose of output through the tool

Plus there are a few other projects on GitHub already with this name

**Comment by norosa** [comment]
Collecting some ideas here:

- polite

**Comment by norosa** [comment]
went with Softener: 8c284c86553928af42168f13408876a82bc755b2

**Comment by norosa** [comment]
or perhaps a better thing to riff off is annotations, annotating, marginalia, etc., because it's not really about formatting error messages, it's about formatting line-by-line file annotations

**Comment by nomiro** [comment]
settled on Obelist

to wit:

> The [obelus] is a typographical mark used to "indicate erroneous or dubious content." The _Oxford English Dictionary_ (OED) defines [obelism] as the "action or practice of marking something as spurious."
>
> Obelist, then, serves as both a verbal noun and a play on words: the program's output is, essentially, _a list of obeluses_.
